### ISSUE TITLE
tenma-72-7730A Driver Problem

### ISSUE THREAD

**Issue by danielelic** [djorlando24/pyLabDataLogger#1]
Hi Daniel,

I try to connect multimeter tenma-72-7730A, but your script (`scan_tenma72-7730a.sh`) doesn't work on my notebook. In order to install your library (`pyLabDataLogger`) I have installed the following packages in advance:
```
sudo apt install sigrok-cli libserialport-dev libsigrok-dev libsigrokdecode-dev
```
and:
```
pip2 install pyusb pyserial numpy cython
```
Moreover, I have created the rules for `udev` service.

```
[15308.033810] usb 1-1.3: new full-speed USB device number 5 using ehci-pci
[15308.143683] usb 1-1.3: New USB device found, idVendor=1a86, idProduct=e008
[15308.143686] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[15308.143688] usb 1-1.3: Product: USB to Serial
[15308.143690] usb 1-1.3: Manufacturer: WCH.CN 
[15308.147616] hid-generic 0003:1A86:E008.0005: hiddev0,hidraw0: USB HID v1.00 Device [WCH.CN  USB to Serial] on usb-0000:00:1d.0-1.3/input0
(venv) user@mynotebook:~/pyLabDataLogger/scripts$ ./scan_tenma72-7730a.sh 
sr: libsigrok loglevel set to 5.
sr: backend: Sanity-checking all drivers.
sr: backend: Sanity-checking all input modules.
sr: backend: Sanity-checking all output modules.
srd: libsigrokdecode loglevel set to 5.
Driver tenma-72-7730 not found.
```

Any suggests?

**Comment by djorlando24** [comment]
Hi, thanks for this.  The cause is that the sigrok version you've installed from the package manager is out-of-date and is missing the 72-7730 driver. Bad news, you'll need to build a newer sigrok from source. Good news is that it's not hard, see https://sigrok.org/wiki/Downloads.  I've found that Ubuntu LTS has a way out of date sigrok build, it's rather useless from a hardware support version.

**Comment by sventurag** [comment]
Hi, I just tried out by doing 
`sudo apt install sigrok-cli libserialport-dev libsigrok-dev libsigrokdecode-dev`
In ubuntu 22, and  it works, but the output is 
`sr: [00:10.211294] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)`

with the number in brackets incrementing continuously, and the same output: f0 00 00 00 00 00 00 00 (0 data bytes).

I am trying to get the temperature and I can see the main screen in the multimeter showing the current non-zero value and the word _SEND_ below, but still the output is zero. Not sure if the multimeter should be in a particular configuration.

This is the output of ./scan_tenma72-7730a.sh :

The following devices were found:
tenma-72-7730 - Tenma 72-7730 with 1 channel: P1
sr: [00:00.000000] log: libsigrok loglevel set to 5.
sr: [00:00.000032] backend: libsigrok 0.5.2/5:1:1.
sr: [00:00.000056] backend: Libs: glib 2.67.5 (rt: 2.72.1/7201:1), libzip 1.7.3, libserialport 0.1.1/1:0:1 (rt: 0.1.1/1:0:1), libusb-1.0 1.0.25.11696 API 0x01000108, hidapi 0.10.1, bluez 5.56, libftdi 1.5.
sr: [00:00.000066] backend: Host: x86_64-pc-linux-gnu, little-endian.
sr: [00:00.000069] backend: SCPI backends: TCP, serial, USBTMC.
sr: [00:00.000077] backend: Firmware search paths:
sr: [00:00.000094] backend:  - /home/sv270040/.local/share/sigrok-firmware
sr: [00:00.000098] backend:  - /usr/share/sigrok-firmware
sr: [00:00.000100] backend:  - /usr/share/ubuntu/sigrok-firmware
sr: [00:00.000103] backend:  - /usr/share/gnome/sigrok-firmware
sr: [00:00.000106] backend:  - /usr/local/share/sigrok-firmware
sr: [00:00.000108] backend:  - /usr/share/sigrok-firmware
sr: [00:00.000111] backend:  - /var/lib/snapd/desktop/sigrok-firmware
sr: [00:00.000127] backend: Sanity-checking all drivers.
sr: [00:00.000133] backend: Sanity-checking all input modules.
sr: [00:00.000135] backend: Sanity-checking all output modules.
sr: [00:00.000149] backend: Sanity-checking all transform modules.
srd: libsigrokdecode loglevel set to 5.
sr: [00:00.051793] hwdriver: sr_config_list(): key 2147418112 (NULL) sdi (nil) cg NULL -> [uint32 20000]
sr: [00:00.051858] usb: Found USB device (VID:PID = 1a86:e008, bus.address = 3.12).
sr: [00:00.051877] hwdriver: Scan found 1 devices (tenma-72-7730).
sr: [00:00.051886] device: tenma-72-7730: Opening device instance.
sr: [00:00.051889] usb: Trying to open USB device 3.12.
sr: [00:00.051913] usb: Opened USB device (VID:PID = 1a86:e008, bus.address = 3.12).
sr: [00:00.051924] hwdriver: sr_config_set(): key 50001 (limit_samples) sdi 0x55c149901840 cg NULL -> uint64 1
sr: [00:00.051935] session: Using thread-default main context.
sr: [00:00.051938] session: Starting.
sr: [00:00.051940] hwdriver: tenma-72-7730: Starting acquisition.
sr: [00:00.051944] session: bus: Received SR_DF_HEADER packet.
cli: Received SR_DF_HEADER.
sr: [00:00.062425] uni-t-dmm: Sending initial HID feature report.
sr: [00:00.062454] uni-t-dmm: HID init = 0x60 0x09 0x00 0x00 0x03 (2400 baud)
sr: [00:00.063734] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.075766] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.087756] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.099755] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.111745] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.123754] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.135763] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.147758] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.159757] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.171763] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)
sr: [00:00.183758] uni-t-dmm: 8-byte chunk: f0 00 00 00 00 00 00 00 (0 data bytes)

**Comment by djorlando24** [comment]
Hi sventurag,

Unfortunately I found that the version of sigrok bundled provided via apt
in Ubuntu etc. does not have functional support for some of these Tenma
devices.
I had to build sigrok from source myself, and then it worked, although
occasionally I had to unplug and replug the USB adapter if only zeros are
coming back.

Good luck!
