### ISSUE TITLE
wrong shebang line?

### ISSUE THREAD

**Issue by MarcoBisi0** [djorlando24/pyLabDataLogger#2]
I think that the shebang line should be **#!/usr/bin/env python3**. I wasn't able to execute **detect_usb_devices** from command line until I change it. Also, in many files shebang line is missing.
I proceed with my testing. Thank you Daniel for your work

**Comment by djorlando24** [comment]
Thank you for noticing the syntax error, it is fixed. Not sure how that happened, possibly a rogue find-and-replace. I usually execute scripts using python3 rather than directly from command line because I have multiple interpreter versions, so I hadn't noticed. Sorry!
